version: '3.8'
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver-container
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "YourPassword"
      ACCEPT_EULA: "Y"
      TRUST_SERVER_CERTIFICATE: "true"

